receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlp:
    endpoint: otlp.nr-data.net:4317
    headers:
      api-key: ${NEW_RELIC_LICENSE_KEY}
    tls:
      insecure: false

  debug:
    verbosity: detailed 

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp, debug]
    metrics:
      receivers: [otlp]
      exporters: [otlp, debug]